name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      # This step is not needed for the newer GitHub Pages deployment process
      # It's included for context in traditional deployment workflows
      #- name: Deploy to GitHub Pages
      #  uses: JamesIves/github-pages-deploy-action@v4
      #  with:
      #    branch: gh-pages
      #    folder: build
      #    clean: true
      #    token: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
